#ifndef CVISUALDEVLIBRARY_HPP
#define CVISUALDEVLIBRARY_HPP

#include <QtCore/QtGlobal>

#if defined(CVISUALDEV_LIBRARY)
#  define CVISUALDEVSHAREDLIB_EXPORT Q_DECL_EXPORT
#else
#  define CVISUALDEVSHAREDLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // CVISUALDEVLIBRARY_HPP
